food_lst = [
         'Cell-based Meat',
         'Chemical Synthesis',
         'Computational Biology',
         'Enzyme',
         'Fermentation Tank',
         'Food-as-Software',
         'Form factor',
         'Fortification',
         'Genetic Engineering',
         'High-throughput Screening',
         'Industrial Agriculture',
         'Macro-organism',
         'Metabolic Engineering',
         'Micro-organism (microbe)',
         'Modern Food',
         'Mycoprotein',
         'Plant-based Meat',
         'Precision Agriculture',
         'Precision Biology',
         'Precision Fermentation',
         'Precision-fermentation Enabled',
         'Precision-fermentation Enhanced',
         'Synthetic Biology',
         'Systems Biology'
]

food_dct = {
    'Cell-based Meat':'Meat that is comprised of animal cells grown outside an animal in a bioreactor. These products are genetically identical to conventional animal products. Cell-based meat is also referred to by others as clean meat, lab-grown meat, cultured meat, or in-vitro meat.',
    'Chemical Synthesis':'The construction of chemical compounds through a series of chemical reactions or physical manipulations to get from precursors (petrochemical or natural) to organic molecules. Synthesis is used to discover compounds with new physical or biological properties, to produce compounds that do not form naturally, or to make products in large quantities. Products created through chemical synthesis are typically referred to as synthetic or man-made and are alternatives to natural products.',
    'Computational Biology':'The application of computers and computer science to the understanding and modeling of the structures and processes of life. Computational biology uses methods from a wide range of mathematical and computational fields (for example complexity theory, algorithmics, machine learning, and robotics) to represent and simulate biological systems (for example molecules, cells, tissues, and organs), and interpret experimental data (for example concentrations, sequences, and images), often on a very large scale.',
    'Enzyme':'A substance that acts as a catalyst, regulating the rate at which chemical reactions proceed without being altered itself.',
    'Fermentation Tank':'A stainless steel, cylindrical vessel that facilitates various types of biochemical reactions by providing agitation, aeration, sterility, and regulation of factorslike temperature, pH, pressure, and nutrient feeding in a closed-system environment. We include bioreactors in this definition. Precision Fermentation uses fermentation tanks while cell-based meat uses bioreactors.',
    'Food-as-Software':'The new model of food production and consumption that adopts certain principles of modern computing. Like software, food products are continually improved through iteration as technology improves in both cost and capability and as food component databases grow. Food is designed using massive databases of molecules and tweaked for variations such as taste and texture based on consumer preferences or nutritional requirements. Integration with information technology and the internet means that improvements in production methods and/or ingredients can be downloaded and incorporated almost instantaneously, allowing production to be fully distributed and decentralized.',
    'Form factor':'The size, shape, and functionality of a food, or other, product. The term “form factor” comes from the computer industry – it is the computer or electronic hardware’s overall design and functionality, usually highlighted by a prominent feature such as a QWERTY keyboard.',
    'Fortification':'Enhancing a product by including elements, such as proteins, that deliver desirable properties like improved nutrition.',
    'Genetic Engineering':'The direct manipulation, modification, or recombination of DNA in order to modify an organism’s (or population of organisms’) characteristics.',
    'High-throughput Screening':'An experimentation process relevant to the fields of chemistry and biology, in which hundreds of thousands of samples are subjected to simultaneous testing under given conditions. Enabled by technological advancement in robotics, sensors, and automation, high-throughput screening can quickly, reliably, and easily generate large datasets that can be used to answer complex biological questions.',
    'Industrial Agriculture':'The industrialized production of livestock, poultry, fish, and crops brought about by the industrial revolution that prioritizes large-scale production, maximum yields, and quick turnover. Industrial agriculture is characterized by confined animal farming operations, chemical pesticides and fertilizers, very large monocrop farming operations, centralized production, and vast distribution networks.',
    'Macro-organism':'An organism that can be seen with the naked eye.',
    'Metabolic Engineering':'The targeted and purposeful alteration of metabolic pathways found in an organism to generate useful products at high productivity.',
    'Micro-organism (microbe)':'An organism that can only be seen with a microscope. Many different types of organisms can be classified as microbes, including bacteria, archaea, fungi, protists, viruses, plants, or animals.',
    'Modern Food':'Food produced by the modern food industry using the new technologies we discuss in this report, be it precision fermentation, cell-based meat, Food-as-Software (which many plant-based foods utilize), or a combination of all.',
    'Mycoprotein':'A single-celled fungal protein product grown by fermentation.',
    'Plant-based Meat':'Meat that is made entirely from plant ingredients but is produced in such a way that it resembles traditional, animal-derived meat products such as burgers, steaks, hot dogs, or jerky. Historically, soy has been the most popular choice as the main ingredient in plant-based meat, but recently companies have been successful using other ingredients like wheat, yellow pea, and coconut. These new ingredients have become more prominent due to advances in technology that have enabled superior functionality, including more meat-like flavor profiles, textures, and appearances.',
    'Precision Agriculture':'Agricultural activity characterized by a strong focus on high-resolution data collection thorough analysis and specific manipulations. Examples include site-specific fertilizer or pesticide application for crop farming, and timed, detailed control of animal care and feeding in livestock. This is distinct from precision biology andprecision fermentation as it represents incremental improvement in efficiency of industrial agriculture.',
    'Precision Biology':'The coming together of modern information technologies like artificial intelligence (AI), machine learning, and the cloud, with modern biotechnologies like genetic engineering, synthetic biology, metabolic engineering, systems biology, bioinformatics, and computational biology.',
    'Precision Fermentation':'Fermentation plus precision biology. A process that allows us to program micro-organisms to produce almost any complex organic molecule.',
    'Precision-fermentation Enabled':'Any product or production technique that is improved, or made possible by, advances in precision fermentation costs or capabilities.',
    'Precision-fermentation Enhanced':'Any product with ingredients made by precision fermentation. These products do not contain animal-derived meat.',
    'Synthetic Biology':'A discipline in which the main objective is to create fully operational existing or novel biological systems from smaller constituent parts, including DNA, proteins, and other organic molecules, by applying engineering principles to biology.',
    'Systems Biology':'A holistic approach to deciphering the complexity of biological systems by studying the interactions and behavior of the components of biological entities (for example molecules, cells, organs, and organisms) with the understanding that the whole of a living organism is more than the sum of its parts. The field integrates biology, computer science, engineering, bioinformatics, and physics.',
}

level_lst = ['Irrelevant', 'Slightly Related', 'Involved', 'Essential']